#!/bin/bash
sudo su
yum install httpd -y
systemctl start httpd 
systemctl eneble httpd 
echo "Hello World from server 2" > /var/www/html/index.html
echo "Hello from feature1 branch" >> /var/www/html/index.html


